# Generated by Django 3.2 on 2021-06-26 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('year', models.CharField(default=2021, max_length=4)),
                ('semester', models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('2/1', '2/1'), ('2/2', '2/2'), ('3/1', '3/1'), ('3/2', '3/2'), ('4/1', '4/1'), ('4/2', '4/2')], default='1/1', max_length=10)),
                ('committee_id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credit', models.FloatField()),
                ('course_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], default='theory', max_length=10)),
                ('year', models.CharField(default=2021, max_length=4)),
                ('committee', models.ForeignKey(default='unassigned', on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.committee')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('teacher_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('is_head', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('complete', 'Completed'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('course', models.ForeignKey(default='unassigned', on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.course')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='committee',
            name='teachers',
            field=models.ManyToManyField(to='teacher.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'year')},
        ),
    ]
