# Generated by Django 3.2 on 2021-06-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api2', '0002_rename_email_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='status',
            field=models.CharField(choices=[('complete', 'Completed'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20),
        ),
    ]
